### PR TITLE
Update README

### PR DESCRIPTION
**Pull request by laszewsk**
There is a difference between USB readers and writers. 

There are USB readers out there that do not allow writing.

### CODE REVIEW

**Comment by spl237** [comment]
Pointless change.

**Comment by laszewsk** [comment]
Well my students bought USB readers and wondered why they could not write ;-)

**Comment by JamesH65** [comment]
Is that even possible? I've never heard of a USB reader that was unable to write.

**Comment by spl237** [comment]
> Is that even possible? I've never heard of a USB reader that was unable to write.

Me neither... And given that the SD card interface is bidirectional even when reading, and USB is bidirectional all the time, it seems unlikely to be possible even to make one if you wanted to!

I suspect the OP's problem lies with bad / faulty SD card readers, not with ones that are designed not to be able to write.

**Comment by laszewsk** [comment]
Thanks for the feedback that made me double-check.  Originally I had the same thought as you. Is this even possible?

They identified the cheapest they could find and we bought 10 the same SDCrad readers from amazon. I just verified that all could not write. All could however read. Then I checked on Amazon and found that the item is no longer listed. Maybe it is a manufacturing defect as they discontinued selling it or maybe it is some cheap design that does not allow writing.

As I sometimes interact with younger students I now always say "SD Card Reader/Writer" and casually just "SD Card Writer" instead of Reader just to be sure. Since I use this terminology they look up SD Card Writer to buy items. I also make sure they know that they need to double-check if the Amazon spec explicitly states "write" in the description, as several products I looked up today actually do not state this. The original spec (which we no longer have did not specify they can write). 

I do not insist that you change it. Our device may be an outlier.

**Comment by spl237** [comment]
With SD cards, it isn't the reader which does the writing; it is the card itself. All the reader does is to pass the data to the card, and to issue a "write" command. (And when it does a read, it issues a "read" command and gets the data from the card - so you have to be able to send to the card to do a read.)

So if a card is not being written to by a reader, it is because either the reader is not issuing the "write" command for some reason - which would be bizarre - or because the card is failing to write - because it is faulty or locked in read-only mode - or possibly because the reader is not supplying enough voltage to energise the write circuitry in the card. I suspect the problem you are seeing is down to a power supply fault in the readers, whereby they can provide enough power to read, but when the write command is issued, the additional power drain from the card cannot be met and the write fails. But this won't be by design; this will be a fault.

**Comment by laszewsk** [comment]
Super! Thanks for the explanation! We are recycling these devices now as the cards that we used in them work in other readers. (Note I use now the word reader ;-)

**Pull request closed without merging**
